### ISSUE TITLE
Limitation on pickle size?

### ISSUE THREAD

**Issue by victornoel** [irmen/pickle#6]
Hello,

I'm using sklearn2jpmml using this pickle library and facing the following error:
```
Exception in thread "main" java.lang.NegativeArraySizeException: -1394647443
    at net.razorvine.pickle.PickleUtils.readbytes(PickleUtils.java:54)
    at net.razorvine.pickle.Unpickler.load_binbytes(Unpickler.java:510)
    at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:315)
    at org.jpmml.python.PickleUtil$1.dispatch(PickleUtil.java:83)
    at net.razorvine.pickle.Unpickler.load(Unpickler.java:109)
    at org.jpmml.python.PickleUtil.unpickle(PickleUtil.java:104)
    at org.jpmml.sklearn.Main.run(Main.java:173)
    at org.jpmml.sklearn.Main.main(Main.java:161)
```

It happens when the model is "too big" apparently, is there known limitations about the size or is that a bug?

**Comment by irmen** [comment]
It seems you indeed exceeded the max array size which is a (signed) 32 bits integer in Java.  
The max size thus is 2^31  = about 2 gigabytes.
If you exceed this, you'll need to serialize less data or chop it up in multiple chunks.

(That's a pretty massive serialized stream by the way, in my book. I don't know your use case but won't this cause problems anyway when sending this across the network or processing it on the receiving end?)

**Comment by victornoel** [comment]
@irmen hehe yes, I agree about the massiveness of the pickle ^^ in this particular  case it's a sklearn pipeline (a machine learning model) that is pickled and converted to PMML a standard format to store such type of machine learning result, so it's not sent over the network or anywhere.

From your answer I understand that:
- it's not a bug, it's a feature
- it's not related to the pickle protocol used and using protocol 5 won't help? (not sure about that one, any feedback would be appreciated :)

**Comment by irmen** [comment]
It's an (undocumented?) feature of the current Java pickle implementation, yeah. I never anticipated pickle streams of more than 2 gigabytes. 

Different pickle protocol levels store data in different ways so perhaps protocol 5 is more efficient, you can certainly try it.

**Comment by victornoel** [comment]
> It's an (undocumented?) feature of the current Java pickle implementation, yeah. I never anticipated pickle streams of more than 2 gigabytes.

heh, I see :) so theoretically speaking, we could improve the java implementation to work around this limitation, for example by chunking what it's reading in multiple arrays but exposing that as if it was one? Or something like this... just an idea, this would depend on how you expose arrays to the user code of course.

Anyway, I will get back to you once I tried with protocol 5, it will maybe solve things and we will just conclude that that's what newer protocol are for!

Thank you for the explanations

**Comment by victornoel** [comment]
Hi @irmen, according to my tests (see https://github.com/jpmml/sklearn2pmml/issues/287#issuecomment-868302788), even though I tried using pickle protocol 5, it seems the same problem happen.

What is surprising, when the array was deserialized, it was interpreted as protocol 3 (as per the stacktrace shared above, `net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:315)`) and not 5.

I'm not familiar with how all of this work, so maybe this is expected, you tell me :)

**Comment by victornoel** [comment]
Also, apparently Python itself is able to pickle/unpickle the file without problem. There is still one thing I'm not sure of, is the fact that the file raising the error is a file that was pickled using joblib, not Python's pickle directly, so there may be some difference there…

**Comment by irmen** [comment]
>  so theoretically speaking, we could improve the java implementation to work around this limitation,

No, that's not what I meant. My suggestion was to make your source system's dataset smaller and/or split up the source data before you pickle it, to avoid having to deal with pickles larger than 2 gigabytes. Then concatenate stuff again after unpickling if you really have to have the >2Gb file again as one huge chunk.

This is something you can do now (I suppose) and continue working with the existing library.

The ultimate solution -should we choose to support "large files" - is going through all the java and C# code in this pickle library to remove any 32 bits integer limits.

**Comment by victornoel** [comment]
I understand.

Unfortunately, I cannot just chunk my arrays, because they are built by another library (sklearn/xgboost), I don't have control on it.

Also, since pickling/unpickling is working fine with Python itself, I am thinking that it would be beneficial to support bigger array size in Java. Do you think the effort would be important to support this?

**Comment by vruusmann** [comment]
> Unfortunately, I cannot just chunk my arrays, 
> because they are built by another library (sklearn/xgboost),
> I don't have control on it.

Let' me guess, you have trained an XGBoost >= 1.3.X model, which is formatted as a >2GB JSON text file, and inserted into a "pickle container" as-is.

Things that could help:

1. Instruct XGBoost to format the model using legacy binary format, not the new and shiny JSON format.
2. Compress the JSON. Should deflate >90%?
3. Store the JSON in an "external resource file", and only pickle a reference to that file.

> I am thinking that it would be beneficial to support bigger array size in Java.

That probably involves switching from `byte[]` type to `java.nio.ByteBuffer` or `List<Byte` type? Probably must use a custom `List` implementation class, because most JDK built-in classes still assume that arrays cannot contain more than 2G elements.

**Comment by irmen** [comment]
> most JDK built-in classes still assume that arrays cannot contain more than 2G elements.

I'm not going to rewrite the current code to work around this any time soon I'm afraid.  Especially if possibilities seem to exist to reduce the pickle size in the originating code.

I'll add the current limitation to the documentation so that it's clear upfront.

**Comment by vruusmann** [comment]
> most JDK built-in classes still assume that arrays cannot contain more than 2G elements.

In principle, one could replace `byte[]` with `int[]` or `long[]`, and thereby be able to store 4 x 2GB or 8 x 2GB worth of `byte` values in a 2G-element Java array.

But I agree - it's not worth the effort, as we're dealing with a very specific case here (storing a very large JSON dump inside a pickle file). Even if the Pickle library is able to work around this limitation, then all the other library/application layers are still likely to break (because of the same 2G byte array limitation) when they try to process this JSON dump.

@irmen I'm a very happy Pyrolite/Pickle user for 5+ years. Never had any any functional issues with it. Most awesome!

**Comment by irmen** [comment]
enlighten me, how do you end up with a multi-gigabyte JSON dump?  That is an excruciatingly inefficient way to store large data sets (thankfully it isn't XML though!)  Secondly, why is this considered to be a byte array when JSON is a text format?  (This won't make any difference for this issue here, but just curious)

**Comment by vruusmann** [comment]
> enlighten me, how do you end up with a multi-gigabyte JSON dump?

There's a machine learning algorithm called [XGBoost](https://en.wikipedia.org/wiki/XGBoost), which approximates functions using a collection of decision trees. The size of the learned XGBoost model is proportional to the size of the training dataset.

If you start with a sufficiently large training dataset, and you let the XGBoost algorithm run with rather lax constraints (number and configuration of decision trees), then you can end up with a very big data structure.

The current issue stems from the fact that XGBoost recently switched from a proprietary binary model serialization format to JSON. What was 20 MB binary dump instantly became a 2 GB JSON dump.

The JSON itself is already whitespace-heavy. Now imagine storing pretty-printed decision trees in JSON! And all the indentation is done using space characters.

> why is this considered to be a byte array when JSON is a text format?

Probably in order to ensure compatibility with the earlier binary dumps.

The `Booster.handle` attribute is of `byte[]` type, so it can store a legacy binary data format data, or the new and shiny JSON data.

Adding a new attribute of `String` type probably wouldn't help, because inside a String there needs to be a `char[]` that still cannot contain more than 2G elements.

**Comment by vruusmann** [comment]
@victornoel You could check the above hypothesis, and actually open an issue with the XGBoost project.

The solution to your problem is a more efficient way of storing big JSON payloads (forced compression?). It should happen in the XGBoost library level.

**Comment by victornoel** [comment]
@irmen from all those discussions, it seems clear that the problem here is really caused by a misuse of pickle format when serializing xgboost models, so I think we can safely say that this pickle library is not at fault :)
I agree that improving the documentation or the error message would be a good solution: I would propose to keep this issue open for this, or we can close it already, as you prefer.

@vruusmann all of what you shared seems very promising, I will test it out as soon as possible, thanks for taking the time to think out loud :) I will share in https://github.com/jpmml/sklearn2pmml/issues/287 the result of my experimentations, hopefully we can add this to the documentation to help other people in the future (or automate it in the code if it makes sense... not sure :)

**Comment by irmen** [comment]
>  XGBoost recently switched from a proprietary binary model serialization format to JSON. What was 20 MB binary dump instantly became a 2 GB JSON dump

I don't know anything about XGBoost, but this sounds like a very silly decision to me. Surely there is a good reason for this, but if it also means you have to deal with a storage format that is several orders of magnitude more inefficient as before, I wonder why they came up with this.

**Comment by irmen** [comment]
Size limitation added to docs in e724f7ca52cca98c2d04c76bdcbcb4f3a4fc6182 therefore now closing this issue.
